### ISSUE TITLE
AvalonDock 3.3: Serialization of hidden panels does not work

### ISSUE THREAD

**Issue by xceedsoftware** [xceedsoftware/wpftoolkit#1126]
<b>Dige[CodePlex]</b> <br />If I try to serialize the layout with two panels hidden the resulting XML will contain an element like this, which obviously is not valid XML and makes deserialization impossible.
  ltHidden AutoHideMinWidth=quot100quot AutoHideMinHeight=quot100quot Title=quotPanel_1quot ContentId=quotPanel_1quot CanClose=quotFalsequot PreviousContainerId=quotf5ef0b3f-a63b-4c9b-9e09-804485d56c53quot PreviousContainerIndex=quot0quot AutoHideMinWidth=quot100quot AutoHideMinHeight=quot100quot Title=quotPanel_2quot ContentId=quotPanel_2quot CanClose=quotFalsequot PreviousContainerId=quotf5ef0b3f-a63b-4c9b-9e09-804485d56c53quot PreviousContainerIndex=quot0quot /gt
The DockingManager uses bindings to show/hide panels:
ltxcad:DockingManager Grid.Row=quot1quot x:Name=quotDockingManagerquot AnchorablesSource=quot{Binding Panels}quot DocumentsSource=quot{Binding Documents}quot AllowMixedOrientation=quotTruequot gt
            ltxcad:DockingManager.LayoutItemContainerStyleSelectorgt
                ltavalonTest:LayoutItemStyleSelectorgt
                    ltavalonTest:LayoutItemStyleSelector.PanelStylegt
                        ltStyle TargetType=quot{x:Type xcad:LayoutItem}quotgt
                            ltSetter Property=quotContentIdquot Value=quot{Binding Model.DataContext.Text}quot/gt
                            ltSetter Property=quotTitlequot Value=quot{Binding Model.DataContext.Text}quot/gt
                            ltSetter Property=quotVisibilityquot Value=quot{Binding Model.DataContext.Visibility, Mode=TwoWay}quot/gt
                        lt/Stylegt
                    lt/avalonTest:LayoutItemStyleSelector.PanelStylegt
                    ltavalonTest:LayoutItemStyleSelector.DocumentStylegt
                        ltStyle TargetType=quot{x:Type xcad:LayoutItem}quotgt
                            ltSetter Property=quotContentIdquot Value=quot{Binding Model.Text}quot/gt
                            ltSetter Property=quotTitlequot Value=quotDocumentquot/gt
                            ltSetter Property=quotVisibilityquot Value=quot{Binding Model.Visibility}quot/gt
                        lt/Stylegt
                    lt/avalonTest:LayoutItemStyleSelector.DocumentStylegt
                lt/avalonTest:LayoutItemStyleSelectorgt
            lt/xcad:DockingManager.LayoutItemContainerStyleSelectorgt
        lt/xcad:DockingManagergt

**Comment by xceedsoftware** [comment]
<b>BoucherS[CodePlex]</b> <br />Hi, 
This is already fixed.
The fix will be included in v3.4.

**Comment by nzain** [comment]
The issues says AvalonDock 3.3 - the latest (community) release on nuget is version 3.2 and it has the same bug.

So you fixed the bug for paying customers a while ago. When will you release more plus versions and finally release the bugfix to the community?

**Comment by XceedBoucherS** [comment]
Hi,

The Plus edition is already at v3.6 and you can get it here : https://xceed.com/xceed-toolkit-plus-for-wpf/.
The community edition will be updated to v3.3 shortly.
Thank you.

**Comment by mjanulaitis** [comment]
I am running the community version 3.3.0.0.  When I save a layout with a hidden view I still see the same XML error:

<?xml version="1.0" encoding="utf-8"?>
<LayoutRoot>
  <RootPanel Orientation="Horizontal">
    <LayoutPanel Orientation="Horizontal">
      <LayoutPanel Orientation="Horizontal">
        <LayoutPanel Orientation="Horizontal">
          <LayoutPanel Orientation="Horizontal" DockHeight="1.38681005157467*">
            <LayoutPanel Orientation="Horizontal">
              <LayoutAnchorablePane Id="96b63cd4-0bbb-41d2-b1ec-27d9b62d6fd8" DockWidth="200">
                <LayoutAnchorable AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Explorer" IsSelected="True" ContentId="ExplorerViewModel" CanClose="False" LastActivationTimeStamp="05/28/2018 09:10:18" />
              </LayoutAnchorablePane>
              <LayoutPanel Orientation="Vertical">
                <LayoutPanel Orientation="Horizontal">
                  <LayoutPanel Orientation="Horizontal">
                    <LayoutPanel Orientation="Horizontal">
                      <LayoutDocumentPane />
                    </LayoutPanel>
                  </LayoutPanel>
                </LayoutPanel>
              </LayoutPanel>
            </LayoutPanel>
          </LayoutPanel>
        </LayoutPanel>
      </LayoutPanel>
    </LayoutPanel>
  </RootPanel>
  <TopSide />
  <RightSide />
  <LeftSide />
  <BottomSide />
  <FloatingWindows />
  <Hidden AutoHideMinWidth="100" AutoHideMinHeight="100" Title="Server Output" ContentId="ServerOutputViewModel" CanClose="False" LastActivationTimeStamp="05/28/2018 09:10:17" PreviousContainerId="96b63cd4-0bbb-41d2-b1ec-27d9b62d6fd8" PreviousContainerIndex="1" />
</LayoutRoot>

**Comment by XceedBoucherS** [comment]
Hi, as said earlier, this issue is fixed in v3.4.
I suggest you wait for v3.4 Community edition to be released....or try the free 45 days trial of v3.6 Plus edition from https://xceed.com/xceed-toolkit-plus-for-wpf/.
Thank you.
