### ISSUE TITLE
DateTimePicker & DateTimeUpDown not update Value until focus lost

### ISSUE THREAD

**Issue by MrQ99** [xceedsoftware/wpftoolkit#1206]
Just updated from v2.9 to v3.2 to resolve a number of issues.
However, now. the value (via data binding) is no longer updated before leaving the control. So changing the time with the up/down spinner etc. has no impact on the underlying value.
Tried see if UpdateValueOnEnter made a difference but this does not appear to be implemented/available for use.
I need to bound data value to update since this re calculates a lot of other derived information that the user must see while changing the date/time etc.
Any advice would be most welcome.

**Comment by XceedBoucherS** [comment]
Hi,
This is already fixed in v3.4

In the meantime, go in file Xceed.Wpf.Toolkit/DateTimeUpDown/Implementation/DateTimeUpDown.cs,
Replace the method "Increment" with :

 private void Increment( int step )
    {
      _fireSelectionChangedEvent = false;

      var currentValue = this.ConvertTextToValue( this.TextBox.Text );
      if( currentValue.HasValue )
      {
        var newValue = this.UpdateDateTime( currentValue, step );
        this.TextBox.Text = newValue.Value.ToString( this.GetFormatString( this.Format ), this.CultureInfo );
      }
      else
      {
        this.TextBox.Text = ( this.DefaultValue != null )
                            ? this.DefaultValue.Value.ToString( this.GetFormatString( this.Format ), this.CultureInfo )
                            : this.ContextNow.ToString( this.GetFormatString( this.Format ), this.CultureInfo );
      }

      if( this.TextBox != null )
      {
        DateTimeInfo info = _selectedDateTimeInfo;
        //this only occurs when the user manually type in a value for the Value Property
        if( info == null )
          info = ( this.CurrentDateTimePart != DateTimePart.Other ) ? this.GetDateTimeInfo( this.CurrentDateTimePart ) : _dateTimeInfoList[ 0 ];

        //whenever the value changes we need to parse out the value into out DateTimeInfo segments so we can keep track of the individual pieces
        this.ParseValueIntoDateTimeInfo( this.ConvertTextToValue( this.TextBox.Text ) );

        //we loose our selection when the Value is set so we need to reselect it without firing the selection changed event
        this.TextBox.Select( info.StartPosition, info.Length );
      }
      _fireSelectionChangedEvent = true;

      this.SyncTextAndValueProperties( true, Text );
    }

**Comment by MrQ99** [comment]
Perfect - many thanks!

**Comment by adamfeather** [comment]
This issue seems to still be occurring when you make a selection via the calendar. Using the up/down arrows changes the value (and so fires the binding) immediately... but if you selected a date using the calendar picker you still have to wait until focus is lost for the underlying value to change.

**Comment by goldie83** [comment]
Still no luck in 3.5.0. After selecting Date & time in calendar the bounded property do not change.

**Comment by kevinman117** [comment]
> Still no luck in 3.5.0. After selecting Date & time in calendar the bounded property do not change.

Yep, same here. This is driving me crazy as the users expect immediate changes when they select a date instead of they have to hit enter first or until the datetimepicker has lost focus. Will this be fixed?

**Comment by XceedBoucherS** [comment]
Hi,
Please look at the release notes to see if your issue is already fixed in a later version than v3.5.
https://github.com/xceedsoftware/wpftoolkit/wiki/Improvements-in-v3.5.0

Maybe this in v3.8 : 
"In DateTimePicker, selecting a new date in the Calendar now immediately modifies the Value property."

You can test the latest v3.8 ersion for free for 45 days here : https://xceed.com/xceed-toolkit-plus-for-wpf/

**Comment by kevinman117** [comment]
Hi,

I have found this comment in the v3.8.0 Plus Edition release notes.

> In DateTimePicker, selecting a new date in the Calendar now immediately modifies the Value property.

So we have to pay for this little feature that everyone expects it to work out of the box?

**Comment by XceedBoucherS** [comment]
No, this feature is free, but the fix was done in v3.8.
You can wait for the free version v3.8 to be released, or use the commercial version, which is already at v3.8.

**Comment by kevinman117** [comment]
Thanks for letting us know. We have to be patient I guess.

**Comment by adamfeather** [comment]
Are there any plans to make v3.8 available as the community edition at some point?

**Comment by XceedBoucherS** [comment]
Yes, 
v4.0 should be released in the beginning of 2020 for the Plus users. 
v3.7 is currently available for the community users. v3.8 is the next version scheduled to be released for the community users.
Thank you.
